
[general]
	#The material blacklist of this module.
	materialBlacklist = []

[recipes]
	#The materials that should not have extruder to plate recipes added.
	toPlateMaterialBlacklist = []
	#The materials that should not have extruder to gear recipes added.
	toGearMaterialBlacklist = []
	#The materials that should not have extruder to rod recipes added.
	toRodMaterialBlacklist = []
	#The materials that should not have extruder to wire recipes added.
	toWireMaterialBlacklist = []
	#The materials that should not have extruder to nugget recipes added.
	toNuggetMaterialBlacklist = []

