
[Common]
	#Allows non default structures [false/true|default:true]
	allowNonDefaultStructures = true
	#Allows distance to target hint on the map tooltip [false/true|default:true]
	allowDistanceToTargetHintInTooltip = true
	#Configures a max search distance in chunks to the target.
	#Range: 50 ~ 10000
	structureSearchDistance = 100

	[Common.StructuresFilter]
		#Configures a comma separated list of excludes of particular structures or entire mods (mod id only). Defaults to minecraft:nether_fossil if no such filter with that name is registered.
		excludes = ["minecraft:nether_fossil"]

